name: Build Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build with Jenkins
        uses: appleboy/jenkins-action@v2
        with:
          url: 'http://20.107.39.99'
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_PASSWORD }}
          job: 'frontend-build'

