name: Build Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build with Jenkins
        uses: jenkins/declarative-action@v1
        with:
          jenkins_url: 'http://20.107.39.99'
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.JENKINS_PASSWORD }}
          jenkins_file_path: 'frontend-build/Jenkinsfile'

